In [1]:
import numpy as np

In [2]:
X = np.array([1,2,3])
X, X.shape, X.ndim, X.size

(array([1, 2, 3]), (3,), 1, 3)

In [3]:
Z = np.zeros((3,2))
O = np.ones((4,4))
F = np.full((3,3), 5)

Z, Z.shape, Z.size, O, F 

(array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 (3, 2),
 6,
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]))

In [4]:
np.random.seed(0)
np.random.randn(2,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721]])

In [5]:
np.linspace(0, 5, 10, dtype=np.float16)

array([0.    , 0.5557, 1.111 , 1.667 , 2.223 , 2.777 , 3.334 , 3.889 ,
       4.445 , 5.    ], dtype=float16)

In [6]:
A = np.ones((3,2))
B = np.zeros((3,2))
np.hstack((A, B)), np.vstack((A,B))

(array([[1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]))

In [7]:
AA = np.concatenate((A, B), axis=1)
np.concatenate((A, B), axis=0), AA

(array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.]]))

In [8]:
AA = AA.reshape((1,12))
AA

array([[1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0.]])

In [9]:
AA = AA.reshape((12,1))
AA

array([[1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.]])

In [10]:
tmp = np.array([1,2,3,4])
tmp.shape

(4,)

In [11]:
tmp.shape[0]

4

In [12]:
tmp = tmp.reshape((tmp.shape[0], 1))
tmp.shape 

(4, 1)

#### faire delete les dimension ou apparait 1

In [13]:
tmp = tmp.squeeze()
tmp.shape

(4,)

In [14]:
S = np.ones((5,5))
S 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
S[:2, 2:]=0
S

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
sub = S[S==0]
sub

array([0., 0., 0., 0., 0., 0.])

In [19]:
U = np.full((4,4), 5)
U[::2, ::2] = 0
U 

array([[0, 5, 0, 5],
       [5, 5, 5, 5],
       [0, 5, 0, 5],
       [5, 5, 5, 5]])

In [20]:
T = np.random.randint(1,5, [4,4])
T 

array([[1, 1, 3, 2],
       [3, 4, 4, 3],
       [1, 2, 2, 2],
       [2, 1, 2, 1]])

In [21]:
T<3 

array([[ True,  True, False,  True],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [22]:
T[T<3]

array([1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1])

# Application

In [41]:
np.random.seed(10)
tab = np.random.randint(0, 10, [3,3])
tab

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9]])

## All, Any

In [39]:
tab.all(axis=0), tab.all(axis=1) # Line, column

(array([ True,  True, False]), array([False, False,  True]))

In [40]:
tab.any(axis=0), tab.any(axis=1)

(array([ True,  True,  True]), array([ True,  True,  True]))

## sum, cumsum, cumprod, min, max, cumsum, argmin, argmax, exp

In [46]:
tab.sum(), tab.sum(axis=0), tab.sum(axis=1)

(41, array([11, 21,  9]), array([13, 10, 18]))

In [50]:
tab.cumsum(axis=0), tab.cumsum(axis=1), tab.cumsum()

(array([[ 9,  4,  0],
        [10, 13,  0],
        [11, 21,  9]], dtype=int32),
 array([[ 9, 13, 13],
        [ 1, 10, 10],
        [ 1,  9, 18]], dtype=int32),
 array([ 9, 13, 13, 14, 23, 23, 24, 32, 41], dtype=int32))

In [53]:
tab.cumprod(axis=0), tab.cumprod(axis=1), tab.cumprod()

(array([[  9,   4,   0],
        [  9,  36,   0],
        [  9, 288,   0]], dtype=int32),
 array([[ 9, 36,  0],
        [ 1,  9,  0],
        [ 1,  8, 72]], dtype=int32),
 array([ 9, 36,  0,  0,  0,  0,  0,  0,  0], dtype=int32))

In [60]:
tab.min(axis=0), tab.min(axis=1), tab.min(), tab.argmin()

(array([1, 4, 0]), array([0, 0, 1]), 0, 2)

In [61]:
tab.max(axis=0), tab.max(axis=1), tab.max(), tab.argmax()

(array([9, 9, 9]), array([9, 9, 9]), 9, 0)

In [62]:
np.exp(tab)

array([[8.10308393e+03, 5.45981500e+01, 1.00000000e+00],
       [2.71828183e+00, 8.10308393e+03, 1.00000000e+00],
       [2.71828183e+00, 2.98095799e+03, 8.10308393e+03]])

## stat
### mean, std, var, corrcoef, unique

In [65]:
tab.mean(), tab.mean(axis=0), tab.mean(axis=1)

(4.555555555555555,
 array([3.66666667, 7.        , 3.        ]),
 array([4.33333333, 3.33333333, 6.        ]))

In [69]:
tab.std(), tab.std(axis=0), tab.std(axis=1)

(3.9189315752329774,
 array([3.77123617, 2.1602469 , 4.24264069]),
 array([3.68178701, 4.02768199, 3.55902608]))

In [72]:
tab.var(), tab.var(axis=0), tab.var(axis=1)

(15.358024691358025,
 array([14.22222222,  4.66666667, 18.        ]),
 array([13.55555556, 16.22222222, 12.66666667]))

In [74]:
np.corrcoef(tab)

array([[ 1.        ,  0.03746396, -0.9412189 ],
       [ 0.03746396,  1.        ,  0.30229833],
       [-0.9412189 ,  0.30229833,  1.        ]])

In [75]:
np.corrcoef(tab)[1,2]

0.30229833381011073

In [76]:
np.unique(tab, return_counts=True)

(array([0, 1, 4, 8, 9]), array([2, 2, 1, 1, 3], dtype=int64))

In [79]:
values, counts = np.unique(tab, return_counts=True)
counts

array([2, 2, 1, 1, 3], dtype=int64)

In [80]:
counts.argsort()

array([2, 3, 0, 1, 4], dtype=int64)

In [81]:
# sort values 
values[counts.argsort()]

array([4, 8, 0, 1, 9])

In [82]:
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'value {i} appeare {j}')

value 4 appeare 1
value 8 appeare 1
value 0 appeare 2
value 1 appeare 2
value 9 appeare 3


### NAN Corrections

In [89]:
A = np.random.randn(5, 5)
A[0,4] = np.nan 
A[1,2] = np.nan 
A 

array([[-0.70707145,  0.54666484,  0.94250041, -2.97959677,         nan],
       [-0.05652072,  0.46088845,         nan, -2.29510333, -1.19592931],
       [-0.33310116, -0.79139077,  0.27417278, -0.51490992, -1.7110712 ],
       [ 0.61229731,  1.10012937,  0.56435253, -0.71279944, -0.26085948],
       [ 0.54842807,  0.60319905,  1.00686114, -0.29442601, -1.42088052]])

In [96]:
A.mean(), np.nanmean(A), np.nanvar(A), np.nanmin(A), np.nanmax(A), np.nanstd(A)

(nan,
 -0.2875724402004502,
 1.1237184273491692,
 -2.979596771061134,
 1.1001293740133287,
 1.0600558604852715)

In [101]:
np.isnan(A), np.isnan(A).sum(), np.isnan(A).sum()/A.size

(array([[False, False, False, False,  True],
        [False, False,  True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]),
 2,
 0.08)

In [103]:
A[np.isnan(A)] = 0
A 

array([[-0.70707145,  0.54666484,  0.94250041, -2.97959677,  0.        ],
       [-0.05652072,  0.46088845,  0.        , -2.29510333, -1.19592931],
       [-0.33310116, -0.79139077,  0.27417278, -0.51490992, -1.7110712 ],
       [ 0.61229731,  1.10012937,  0.56435253, -0.71279944, -0.26085948],
       [ 0.54842807,  0.60319905,  1.00686114, -0.29442601, -1.42088052]])

## Linear algera

In [104]:
A = np.ones((3,2))
B = np.ones((2,3))

In [107]:
A, A.shape, A.T, A.T.shape

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 (3, 2),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 (2, 3))

In [109]:
A.dot(B), B.dot(A)

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[3., 3.],
        [3., 3.]]))

### linalg

In [113]:
np.linalg.det(A.dot(B))

0.0